=== Fishlulu1314/SSE18_Homework_FishluuDev/XML&Web/Experiment1/1023.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="college">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="grade" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="class" minOccurs="2" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="student" minOccurs="1" maxOccurs="3"/>
									</xs:sequence>
									<xs:attribute name="cid" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" type="xs:integer"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="student">
		<xs:complexType mixed = "true">
			<xs:sequence>
				<xs:element name="id">
					<xs:complexType>
						<xs:attribute name="sid" type="xs:integer"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="email" type="xs:string"/>
				<xs:element name="tel">
					<xs:complexType>
						<xs:attribute name="no" type="xs:positiveInteger"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="address">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="province" type="xs:string"/>
							<xs:element name="city" type="xs:string"/>
							<xs:element name="detail">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="postcode" type="xs:positiveInteger" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Fishlulu1314/SSE18_Homework_FishluuDev/XML&Web/Experiment1/1023.xml
<?xml version="1.0" encoding="UTF-8"?>
<college xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://Mac/Home/Downloads/1023.xsd">
	<grade type="2020">
		<class cid="2020211504">
			<student>Bill
				<id sid="2020211985"/>
				<email>bill@bupt.edu.cn</email>
				<tel no="17668882222"/>
				<address>
					<province>Shanxi</province>
					<city>Taiyuan</city>
					<detail postcode="345678">No10,Center Steert</detail>
				</address>
			</student>
			<student>Andy
				<id sid="2020211996"/>
				<email>ilove996@bupt.edu.cn</email>
				<tel no="17668886666"/>
				<address>
					<province>Guangdong</province>
					<city>Guangzhou</city>
					<detail postcode="345988">No12,XiDong Steert</detail>
				</address>
			</student>
		</class>
		<class cid="2020211505">
			<student>Alex
				<id sid="2020211999"/>
				<email>test@bupt.edu.cn</email>
				<tel no="17668881111"/>
				<address>
					<province>Beijing</province>
					<city>Xicheng</city>
					<detail postcode="100001">No1,ChangAn Steert</detail>
				</address>
			</student>
		</class>
	</grade>
</college>
